import assert from 'node:assert/strict';
import {els} from './game-environment.mjs';
let seed=31;Math.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const {state,engines,onCall,selectIncident,engageUnits,tickEngines,vehicleObstacles}=await import('../dist/scene.js');
const {incidentState}=await import('../dist/incident-state.js');
const {objectiveResult}=await import('../dist/reinforcements.js');
const {footprint,overlaps}=await import('../dist/vehicle-spacing.js');
const {recallCrew}=await import('../dist/crew.js');
const count=Number(process.env.TEST_VSAVS||2);if(count===4)recallCrew(state,1);
state.schedule=[];state.shiftEnd=100000;
const c={id:1,type:'SUAP',name:'Deux personnes blessées',requires:'VSAV',at:state.minute,status:'waiting',duration:24,progress:0,victimCount:count,patients:Array.from({length:count},()=>({severe:false,evacuated:false,assignedTo:null,transportRequired:true}))};
state.calls.push(c);onCall(c);selectIncident(c.id);const ambulances=engines.filter(e=>e.kind==='VSAV').slice(0,count);assert.equal(engageUnits(ambulances.map(e=>e.id)),null);
const first=engines.find(e=>e.id==='VSAV 1'),second=engines.find(e=>e.id==='VSAV 2');
const step=()=>{state.minute+=.25;tickEngines(.25);for(const e of ambulances)for(const other of vehicleObstacles())if(other!==e.model&&other.visible!==false)assert(!overlaps(footprint(e.model),footprint(other)),e.id+' collision');};
const until=(predicate,label)=>{for(let i=0;i<6000&&!predicate();i++)step();if(!predicate())console.log(JSON.stringify({mission:c.status,patients:c.patients,vehicles:ambulances.map(e=>({id:e.id,status:e.status,call:e.call,point:[e.model.position.x,e.model.position.z],wait:e.controlWaiting,traffic:e.trafficWaiting,segment:e.segment,path:e.path?.slice(e.segment,e.segment+4)}))},null,2));assert(predicate(),label);};
until(()=>[first,second].some(e=>e.status==='transport'),'first transport starts');
selectIncident(c.id);assert.equal(state.completed,0);assert.notEqual(c.status,'closed');assert(els.get('callList').innerHTML.includes('data-call="1"'));
const moving=[first,second].find(e=>e.status==='transport');assert.equal(moving.call,c.id);assert(els.get('incidentPanel').innerHTML.includes('data-track="'+moving.id+'"'));
until(()=>c.siteCompletedAt!=null,'all casualties are loaded');
const onsiteObjective=objectiveResult(c).finish;
assert.equal(incidentState(c,engines).key,'transport');assert(incidentState(c,engines).detail.includes('Centre hospitalier'));
until(()=>c.patients.some(p=>p.deliveredAt!=null),'first hospital handover');
assert.notEqual(c.status,'closed','other ambulance still has its patient');assert.equal(state.completed,0);
until(()=>c.status==='closed','last patient handed over');
assert(c.patients.every(p=>p.hospitalAt!=null&&p.deliveredAt>=p.hospitalAt+15));assert.equal(state.completed,1);assert.equal(objectiveResult(c).finish,onsiteObjective);
selectIncident(c.id);assert(!els.get('callList').innerHTML.includes('data-call="1"'));assert.equal(first.call,null);assert.equal(second.call,null);
assert(state.logs.some(l=>l.message.includes('remise(s) au service des urgences')));
until(()=>ambulances.every(e=>e.status==='ready'),'all ambulances return to the CIS');
console.log('PASS',count,'VSAV: mission remains visible until last hospital handover, one-way CH access and complete returns without collisions');
