import assert from 'node:assert/strict';
import {els} from './game-environment.mjs';
import * as T from '../dist/vendor/three.module.js';
import {fleet} from '../dist/sim.js';
import {defaultComposition,composedFleet,compositionErrors,modelKey,saveComposition,loadComposition,STATION_KEY} from '../dist/station-config.js';
import {vehicle,addAmbulanceDoors} from '../dist/models.js';
import {initWater,setNozzle,tickEquipment,tickWater,stow,equipmentBusy,nozzleLimit,pumpCapacity} from '../dist/hydraulics.js';
import {firstAidFire,fireCapable,engagementError} from '../dist/operations.js';
import {tickPatientHealth} from '../dist/patient-health.js';
import {vehicleConsole} from '../dist/vehicle-console.js';
import {saveGuard,readGuard,decodeGuard} from '../dist/guard-save.js';

const rows=defaultComposition(fleet);rows[rows.findIndex(r=>r.type==='VSAV')].type='PS';
const saved=new Map(),storage={getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)};
assert.deepEqual(compositionErrors(rows),[]);assert(!saveComposition(rows,fleet,storage).error);
const spec=composedFleet(fleet,loadComposition(fleet,storage)).find(e=>e.firstAid);
assert.equal(modelKey(spec),'PS');assert.equal(spec.id,'PS 1');assert.equal(spec.size,6);
const model=vehicle(new T.Scene(),spec.kind,undefined,spec);addAmbulanceDoors(model);
assert.equal(model.userData.bodyStyle,'premier-secours');assert.equal(model.userData.wheels.length,4);
assert.equal(model.userData.rearDoors.length,2);assert.equal(vehicle(new T.Scene(),'PC').userData.wheels.length,4);
assert.equal(vehicle(new T.Scene(),'VPCE').userData.wheels.length,6,'Load carrier keeps its tandem axle');
const ps={...spec,model,status:'scene',crew:6};initWater(ps);
assert.equal(ps.capacity,880);assert.equal(pumpCapacity(ps),2000);assert.equal(nozzleLimit(ps),2);
assert(!setNozzle(ps,'large',1));assert(setNozzle(ps,'ldt',1));tickEquipment(ps,10);tickWater(ps,1);
assert.equal(ps.flow,110);assert.equal(ps.water,770);
ps.hydrant={position:new T.Vector3()};tickEquipment(ps,20);assert.equal(nozzleLimit(ps),2,'Supply team becomes available once connected');
stow(ps);tickEquipment(ps,20);
for(const scene of ['bin','vehicle','motorcycle'])assert(firstAidFire({type:'INC',scene}));
for(const c of [{type:'INC',scene:'house'},{type:'INC',scene:'forest',requires:'CCF'},{type:'INC',scene:'vehicle',electricVehicle:true},{type:'INC',scene:'bin',site:{kind:'building'}}])assert(!fireCapable(ps,c));
const fire={id:800,type:'INC',scene:'bin',status:'active',reconComplete:true};
const panel=vehicleConsole(ps,{incident:fire});assert(panel.includes('1 lance diphasique'));assert(!panel.includes('data-nozzle="large"'));
ps.status='ready';ps.water=0;
assert.match(engagementError([ps],fire,50),/citerne vide/);assert.equal(engagementError([ps],{type:'SUAP',status:'waiting'},50),null);
const casualty={id:801,type:'SUAP',status:'active',reconComplete:true,victimsKnown:true,victimCount:1,patients:[{severe:true,health:70}]};
ps.status='scene';ps.call=801;setNozzle(ps,'ldt',1);tickPatientHealth(casualty,[ps],2,2);assert(casualty.patients[0].health<70,'PS pump crew cannot simultaneously treat the casualty');
stow(ps);tickEquipment(ps,20);const health=casualty.patients[0].health;tickPatientHealth(casualty,[ps],2,4);assert.equal(casualty.patients[0].health,health);
console.log('PASS PS composition, original model, PC single rear axle, 880 L / 110 L/min, two lines, mission limits and separate fire/medical crews');

globalThis.localStorage=storage;let seed=67;Math.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const game=await import('../dist/scene.js');game.state.schedule=[];game.state.shiftEnd=100000;
const unit=game.engines.find(e=>e.firstAid);assert(unit);
const c={id:802,type:'INC',scene:'bin',setting:'sidewalk',name:'Feu de poubelle avec blessé',requires:'FPT',at:game.state.minute,status:'waiting',duration:30,progress:0,evacuated:0,victimCount:1,patients:[{severe:false,evacuated:false,assignedTo:null,transportRequired:true}],allowComplications:false};
game.state.calls.push(c);game.onCall(c);game.selectIncident(c.id);assert.equal(game.engageUnits([unit.id]),null);assert.equal(unit.crew,6);assert.equal(unit.crewIds.length,6);
const step=()=>{game.state.minute+=.25;game.tickEngines(.25);};
const until=(predicate,label)=>{for(let i=0;i<7000&&!predicate();i++)step();assert(predicate(),label+' '+JSON.stringify({status:unit.status,fire:c.progress,contained:c.fireContained,water:unit.water,patient:unit.patientProgress,call:c.status,scene:c.scene,site:c.site,recon:c.reconComplete,hoses:unit.hoses,work:unit.workActive,command:unit.command}));};
until(()=>unit.status==='scene','PS reaches small fire');assert(setNozzle(unit,'ldt',1));
until(()=>c.fireContained,'PS extinguishes bin using its tank');assert(unit.water>0);assert(!c.patients[0].evacuated);assert(equipmentBusy(unit));
for(let i=0;i<20;i++){step();assert(!c.patients[0].evacuated,'No departure while packing equipment');}
until(()=>unit.status==='transport','PS loads patient after folding hoses');assert(!equipmentBusy(unit));assert.equal(unit.nozzles.ldt,0);assert.equal(unit.hydrant,null);assert(c.patients[0].evacuated);
until(()=>c.status==='closed','PS delivers casualty to hospital');assert(c.patients[0].deliveredAt>=c.patients[0].hospitalAt+15);assert.equal(game.state.completed,1);
until(()=>unit.status==='ready','PS returns and refills at CIS');assert.equal(unit.water,880);
game.selectEngine(unit);assert(els.get('vehiclePanel').innerHTML.includes('PS 1'));
assert.equal(saveGuard(game.state,game.engines,[],game.camera,game.controls,storage),null);
const guard=readGuard(storage);assert(guard.specs.find(e=>e.id===unit.id).firstAid);assert(decodeGuard(guard.graph).engines.find(e=>e.id===unit.id).firstAid);
console.log('PASS six crew leave CIS, PS extinguishes fire, stows equipment, transports victim to CH, returns/refills and persists its identity');
