import assert from 'node:assert/strict';
import {els} from './game-environment.mjs';
import * as T from '../dist/vendor/three.module.js';
import {initWater,tickWater,tickEquipment,waterMinutes,stow} from '../dist/hydraulics.js';
import {initFoam,foamError,toggleFoam,tickFoam,decayFoam,foamPower} from '../dist/foam.js';
import {createFoamVisuals} from '../dist/foam-visuals.js';
const c={id:42,type:'INC',scene:'vehicle',status:'active',progress:0,reconComplete:true,actionPoint:[10,20]};
const e={kind:'FPT',status:'scene',call:42};initWater(e);initFoam(e);
assert(foamError(e,{...c,reconComplete:false}));assert(foamError(e,{...c,scene:'house'}));
assert.equal(toggleFoam(e,c),null);assert.equal(e.nozzles.small,1);
tickWater(e,waterMinutes(1));tickFoam(e,c,1);assert.equal(e.foamReserve,120);assert.equal(e.foamFlow,0,'No foam before hose deployment');
tickEquipment(e,20);const water=e.water;tickWater(e,waterMinutes(1));tickFoam(e,c,1);
assert(Math.abs(e.water-(water-250/6))<1e-6,'Water counted once');assert(Math.abs(e.foamReserve-118.75)<1e-6);assert.equal(e.foamFlow,250);assert(c.foamCoverage>0);
e.nozzles.large=1;tickEquipment(e,28);tickWater(e,waterMinutes(1));tickFoam(e,c,1);assert.equal(e.foamFlow,250,'Only first small nozzle receives foam, not large lance');
e.water=0;const before=e.foamReserve;tickWater(e,waterMinutes(1));tickFoam(e,c,1);assert.equal(e.foamReserve,before);assert.equal(e.foamFlow,0);
e.water=100;e.foamReserve=.1;const messages=[];tickWater(e,waterMinutes(1));tickFoam(e,c,1,m=>messages.push(m));assert.equal(e.foamReserve,0);assert.equal(e.foamOn,false);assert.equal(messages.length,1);
assert(foamPower(c)>1&&foamPower(c)<=1.2);assert.equal(foamPower({...c,scene:'house'}),1);
const world=new T.Scene(),visual=createFoamVisuals(world);visual.update([c]);const carpet=visual.records.get(42);assert(carpet);assert.equal(carpet.children.length,24);assert.equal(carpet.position.x,10);
const geometry=carpet.children[0].geometry;visual.update([c]);assert.equal(visual.records.get(42).children[0].geometry,geometry,'Geometry reused');
decayFoam(c,180);visual.update([c]);assert.equal(visual.records.size,0);visual.dispose();
e.foamReserve=30;toggleFoam(e,c);stow(e);assert(!e.foamOn);assert.equal(e.foamFlow,0);
let seed=73;Math.random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32);
const game=await import('../dist/scene.js');const {state,engines,onCall,tickEngines,selectEngine,engageUnits,selectIncident}=game;
state.schedule=[];state.shiftEnd=100000;
const fire={id:1,type:'INC',name:'Feu de véhicule',allowComplications:false,at:state.minute,status:'waiting',progress:0};state.calls.push(fire);onCall(fire);selectIncident(1);
const pump=engines.find(x=>x.id==='FPTSR');assert.equal(engageUnits([pump.id]),null);
function until(condition,label){for(let i=0;i<5000&&!condition();i++){state.minute+=.25;tickEngines(.25);}assert(condition(),label);}
until(()=>pump.status==='scene'&&fire.reconComplete,'Arrival and reconnaissance');
assert(game.toggleHydrant(pump),'Connect the real hydrant for a sustained attack');
els.get('fleet').onclick({target:{closest:s=>s==='[data-engine]'?{dataset:{engine:pump.id}}:null}});assert(els.get('vehiclePanel').innerHTML.includes('data-foam'));
els.get('vehiclePanel').onclick({target:{closest:s=>s==='[data-foam]'?{}:null}});assert(pump.foamOn,'Actual button starts foam');
until(()=>pump.foamFlow>0,'Established foam jet');assert(fire.progress>0&&fire.progress<1);assert(pump.water<=pump.capacity&&pump.foamReserve<pump.foamCapacity);assert(pump.water<pump.capacity||pump.hydrant&&pump.supplyProgress===1,'A full tank during attack requires an established supply');
globalThis.frame(performance.now());assert(pump.hoseVisuals.some(l=>l.jet.visible&&l.jet.material.opacity===.95),'White foam jet renders');
until(()=>fire.fireContained,'Vehicle fire extinguished');assert(!pump.foamOn);assert(fire.foamCoverage>0,'Carpet remains after extinguishing');
until(()=>pump.status==='ready','Hoses packed and truck returned');assert.equal(pump.foamReserve,pump.foamCapacity,'Emulsifier refilled only at CIS');
console.log('PASS foam eligibility, automatic deployment, dosing, water accounting, exhaustion fallback, carpet lifecycle, real command and complete fire mission');
