import assert from 'node:assert/strict';
import {createRadioVoice,spokenRadio} from '../dist/radio-voice.js';
let clock=1000,on=true,cancelled=0,spoken=[],speaking=false;
const synth={getVoices:()=>[{lang:'fr-FR',localService:true,name:'fr'}],speak(u){spoken.push(u);u.onstart();},cancel(){cancelled++;}};
const voice=createRadioVoice({synth,Utterance:class{constructor(text){this.text=text;}},now:()=>clock,enabled:()=>on,onSpeaking:v=>{speaking=v;}});
assert.equal(spokenRadio('FPTSR alimentation en cours.'),null,'Routine controls do not fill the spoken channel');
assert.match(spokenRadio('VSAV 1 — une victime à bord, départ vers le CH.'),/centre hospitalier/);
voice.enqueue('FPTSR prend le départ — en route sur les lieux.');assert.equal(spoken.length,0,'Wait for user activation');
voice.activate();assert.equal(spoken.length,1);assert.equal(spoken[0].lang,'fr-FR');assert(speaking);
voice.enqueue('FPTSR prend le départ — en route sur les lieux.');assert.equal(voice.pending(),0,'No duplicate radio');
voice.enqueue('VSAV 1 prend le départ.');voice.enqueue('Radio · FPTSR · n°2 : Besoin de renfort.',true);
assert.equal(spoken.length,1,'Never overlap announcements');spoken[0].onend();assert.match(spoken[1].text,/renfort/,'Urgent report goes first');
voice.sync(true);assert(!voice.speaking()&&!speaking);assert(cancelled>0);
spoken[1].onend();assert.equal(spoken.length,2,'Cancelled callbacks cannot resume speech');
voice.sync(false);assert.equal(spoken.length,3);assert.match(spoken[2].text,/V S A V/);
on=false;voice.sync();assert.equal(voice.pending(),0);assert(!voice.speaking());
on=true;voice.setMuted(true);assert(!voice.enqueue('VSAV 2 prend le départ.'));voice.setMuted(false);
voice.sync(true);for(let i=0;i<12;i++)voice.enqueue(`Radio · CIS : Intervention numéro ${i}.`);assert.equal(voice.pending(),5);
clock+=46000;voice.sync(false);assert.equal(voice.pending(),0,'Old messages expire instead of playing after a long pause');
voice.enqueue('Radio · CIS : Message de contrôle.');clock+=19000;voice.sync();assert(!voice.speaking(),'Watchdog recovers a missing browser end callback');
voice.sync(true);voice.enqueue('Radio · CIS : Essai radio.',true,true);voice.sync(true);assert(voice.speaking(),'A deliberate sound test works while the game is paused');voice.setMuted(true);assert(!voice.speaking());
const unsupported=createRadioVoice({synth:null,Utterance:null});assert(!unsupported.supported);assert(!unsupported.enqueue('VSAV prend le départ.'));unsupported.activate();unsupported.sync();
console.log('PASS spoken radio: activation, priority, deduplication, mute/pause, bounded queue, expiry and unavailable speech support');
